# Generated by Django 4.0.3 on 2023-05-17 08:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('donation', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statement', models.FileField(upload_to=users.models.overwrite_upload_to)),
                ('Cheques', models.FileField(upload_to=users.models.overwrite_upload_to)),
                ('Direct_Debit', models.FileField(upload_to=users.models.overwrite_upload_to)),
                ('EFTs', models.FileField(upload_to=users.models.overwrite_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='StatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statement', models.FileField(upload_to=users.models.overwrite_upload_to)),
            ],
        ),
    ]
