# Generated by Django 4.1.2 on 2023-05-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_donor_file_statfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statfile',
            old_name='Statement',
            new_name='pstatement',
        ),
    ]
